enum MutationTypes {
  CHANGE_CURRENT_STEP = 'CHANGE_CURRENT_STEP',
  CHANGE_SELECTED_SERVICE = 'CHANGE_SELECTED_SERVICE',
  CHANGE_SELECTED_STAFF = 'CHANGE_SELECTED_STAFF',
  CHANGE_SELECTED_DATETIME = 'CHANGE_SELECTED_DATETIME',
  CHANGE_PERSONAL_DETAILS = 'CHANGE_PERSONAL_DETAILS',
  CHANGE_RESERVED_APPOINTMENTS = 'CHANGE_RESERVED_APPOINTMENTS',
}

export default MutationTypes;
